# Generated by Django 6.0 on 2025-12-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
