# Generated by Django 6.0 on 2025-12-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='default_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_at',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('HAIR', 'Hair'), ('SKIN', 'Skin'), ('OTHER', 'Other')], default='HAIR', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
