# Generated by Django 6.0 on 2025-12-17 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_treatment', models.CharField(blank=True, max_length=200)),
                ('henna_or_black', models.CharField(blank=True, choices=[('HENNA', 'Henna'), ('BLACK', 'Black')], max_length=20)),
                ('home_remedies', models.BooleanField(default=False)),
                ('home_remedy_details', models.TextField(blank=True)),
                ('hair_oil', models.BooleanField(default=False)),
                ('hair_oil_details', models.TextField(blank=True)),
                ('shampoo', models.CharField(blank=True, max_length=100)),
                ('conditioner', models.CharField(blank=True, max_length=100)),
                ('hair_loss', models.BooleanField(default=False)),
                ('dandruff', models.BooleanField(default=False)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hair_condition', to='consultations.consultation')),
            ],
        ),
    ]
