# Generated by Django 6.0 on 2025-12-17 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_haircondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('DRY', 'Dry'), ('OILY', 'Oily'), ('COMBINATION', 'Combination'), ('SENSITIVE', 'Sensitive')], max_length=20)),
                ('sun_exposure', models.CharField(blank=True, choices=[('NEVER', 'Never'), ('LIGHT', 'Light (1–2 hr)'), ('MODERATE', 'Moderate (2–3 hr)'), ('EXCESSIVE', 'Excessive (3–5 hr)')], max_length=20)),
                ('acne', models.BooleanField(default=False)),
                ('dullness', models.BooleanField(default=False)),
                ('pigmentation', models.BooleanField(default=False)),
                ('wrinkles', models.BooleanField(default=False)),
                ('dryness', models.BooleanField(default=False)),
                ('comedones', models.BooleanField(default=False)),
                ('home_remedies', models.BooleanField(default=False)),
                ('home_remedy_details', models.TextField(blank=True)),
                ('night_cream', models.BooleanField(default=False)),
                ('night_cream_details', models.TextField(blank=True)),
                ('cleanser', models.CharField(blank=True, max_length=100)),
                ('toner', models.CharField(blank=True, max_length=100)),
                ('moisturiser', models.CharField(blank=True, max_length=100)),
                ('sunscreen', models.CharField(blank=True, max_length=100)),
                ('serum', models.CharField(blank=True, max_length=100)),
                ('other', models.TextField(blank=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skin_condition', to='consultations.consultation')),
            ],
        ),
    ]
