# Generated by Django 6.0 on 2025-12-17 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_skincondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy', models.BooleanField(default=False)),
                ('pcod', models.BooleanField(default=False)),
                ('thyroid', models.BooleanField(default=False)),
                ('diabetic', models.BooleanField(default=False)),
                ('allergies', models.BooleanField(default=False)),
                ('allergy_details', models.TextField(blank=True)),
                ('medication', models.BooleanField(default=False)),
                ('medication_details', models.TextField(blank=True)),
                ('vitamin_d_deficiency', models.BooleanField(default=False)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_condition', to='consultations.consultation')),
            ],
        ),
    ]
