# Generated by Django 6.0 on 2025-12-18 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_consultationservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='consultation_media/')),
                ('media_type', models.CharField(choices=[('BEFORE', 'Before'), ('AFTER', 'After')], max_length=10)),
                ('category', models.CharField(choices=[('HAIR', 'Hair'), ('SKIN', 'Skin')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='consultations.consultation')),
            ],
        ),
    ]
