# Generated by Django 6.0 on 2025-12-18 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_consultationmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_treatment', models.TextField(blank=True)),
                ('short_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='consultations.consultation')),
            ],
        ),
    ]
