# Generated by Django 6.0 on 2026-01-11 10:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_consultationsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationmedia',
            name='media_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='consultation_media'),
        ),
    ]
